### PR TITLE
Add log types for ManageWiki log

### PR DESCRIPTION
**Pull request by dmehus**
I think I've done this correctly, copying the log types from https://github.com/miraheze/ManageWiki/blob/master/extension.json formatting as per https://github.com/miraheze/CreateWiki/blob/master/extension.json above

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
We can't do rights by itself as it conflicts with core. We need to do extra magic there to make it determine ManageWiki or UserRights

**Comment by dmehus** [comment]
> We can't do rights by itself as it conflicts with core. We need to do extra magic there to make it determine ManageWiki or UserRights

Okay, yeah, wondered about that / how that'd work. Wouldn't `delete` also conflict, though? I thought maybe they wouldn't, though, since they're only applying to the `Special:Log/managewiki`. Anyway, if they _would_ still conflict, I'm not sure how to do that, so maybe you, MacFan4000, or Sario can do a PR to my patch-1?

**Comment by RhinosF1** [comment]
> > We can't do rights by itself as it conflicts with core. We need to do extra magic there to make it determine ManageWiki or UserRights
> 
> Okay, yeah, wondered about that / how that'd work. Wouldn't `delete` also conflict, though? I thought maybe they wouldn't, though, since they're only applying to the `Special:Log/managewiki`. Anyway, if they _would_ still conflict, I'm not sure how to do that, so maybe you, MacFan4000, or Sario can do a PR to my patch-1?

Remove the ones that conflict and then we'll look at them in a future PR

**Review by RhinosF1 — COMMENTED** [review]
Are we sure undelete doesn't conflict?

**Pull request closed without merging**
